add_newline = false

[directory]
truncation_length = 0
truncate_to_repo = false

[git_state]
progress_divider = " of "

[git_status]
conflicted = "âš”ï¸ "
ahead = "ğŸï¸ Ã—${count}"
behind = "ğŸ¢ Ã—${count}"
diverged = "ğŸ”± â‡¡${ahead_count}â‡£${behind_count}"
untracked = "ğŸ›¤ï¸ Ã—${count}"
stashed = "ğŸ“¦ Ã—${count}"
modified = "ğŸ“Ã—${count}"
staged = "ğŸ—ƒï¸ Ã—${count}"
renamed = "ğŸ“›Ã—${count}"
deleted = "ğŸ—‘ï¸ Ã—${count}"

[hostname]
ssh_only = false

[status]
disabled = false
symbol = "ğŸ’£"

[time]
disabled = false
format = "[$time](yellow) "
utc_time_offset = "+2"

[username]
format = "[$user]($style) @ "
show_always = true

